"""Add database indexes for performance

Revision ID: 70fb09a2597b
Revises: 
Create Date: 2025-07-14 11:08:54.478400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fb09a2597b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_is_approved'), ['is_approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_is_featured'), ['is_featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_view_count'), ['view_count'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_view_count'))
        batch_op.drop_index(batch_op.f('ix_portfolio_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_updated_at'))
        batch_op.drop_index(batch_op.f('ix_portfolio_title'))
        batch_op.drop_index(batch_op.f('ix_portfolio_location'))
        batch_op.drop_index(batch_op.f('ix_portfolio_is_public'))
        batch_op.drop_index(batch_op.f('ix_portfolio_is_featured'))
        batch_op.drop_index(batch_op.f('ix_portfolio_is_approved'))
        batch_op.drop_index(batch_op.f('ix_portfolio_created_at'))

    # ### end Alembic commands ###
